# A Importância do NumPy na Ciência de Dados e Computação Científica

NumPy (Numerical Python) é uma biblioteca fundamental para computação científica em Python. Ele fornece:
- Objetos de array multidimensionais de alto desempenho
- Ferramentas para trabalhar com esses arrays
- Funções matemáticas otimizadas

Vamos explorar por que o NumPy é tão importante e mostrar alguns exemplos práticos.

## Por que o NumPy é importante?

1. **Desempenho**: Operações vetorizadas são muito mais rápidas que loops em Python puro
2. **Eficiência de memória**: Arrays NumPy ocupam menos espaço que listas Python
3. **Funcionalidades avançadas**: Álgebra linear, transformadas de Fourier, geração de números aleatórios
4. **Base para outras bibliotecas**: Pandas, SciPy, scikit-learn e matplotlib são construídos sobre NumPy
5. **Interface unificada**: Sintaxe consistente para operações com arrays

In [ ]:
# Importação
import numpy as np
import time
import sys


In [ ]:
# Comparacao Python vs Numpy

py_list = list(range(1000000))
np_array = np.arange(1000000)

# Soma com python
start = time.time()
sum_py = sum(py_list)
py_time = time.time() - start

# Soma com Numpy
start - time.time()
sum_np = np.sum(np_array)
np_time = time.time() - start

print(f"Tempo Python: {py_time:.5f}segundos")
print(f"Tempo Numpy: {np_time:.5f}segundos")
print(py_time/np_time)

In [ ]:
print(f"Tamanho da lista Python: {sys.getsizeof(py_list)}")
print(f"Tamanho da lista Numpy: {sys.getsizeof(np_array)}")

In [11]:
# Operações matemáticas

a = np.array([1,2,3,4,5,6])
b = np.array([7,8,9,10,11,12])

print("Soma: ", a+b)
print("Multiplicação: ", a * b)
print("Exponenciação: ", a **b)
print("Seno: ", np.sin(a))

Soma:  [ 8 10 12 14 16 18]
Multiplicação:  [ 7 16 27 40 55 72]
Exponenciação:  [         1        256      19683    1048576   48828125 2176782336]
Seno:  [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]


In [12]:
# Testes Dentro do array

result_where = np.where(a > 2, 'Maior', 'Menor')
print(result_where)

['Menor' 'Menor' 'Maior' 'Maior' 'Maior' 'Maior']


In [13]:
# Empilhar Arrays

result_stack = np.column_stack((a,b))
print(result_stack)


[[ 1  7]
 [ 2  8]
 [ 3  9]
 [ 4 10]
 [ 5 11]
 [ 6 12]]


In [15]:
# Operações Matriciais

A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

print(A)

print(B)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [18]:
arr = np.arange(1,26).reshape(5,5)
print(arr)

print("Primeira linha: ", arr[0])
print("Ultima coluna: ", arr[:, -1])

print("Valores > 10: ", arr[arr > 10])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
Primeira linha:  [1 2 3 4 5]
Ultima coluna:  [ 5 10 15 20 25]
Valores > 10:  [11 12 13 14 15 16 17 18 19 20 21 22 23 24 25]


In [20]:
# Escalares

c = 4

print("Soma (a + c): ", a + c)

matrix_one = np.ones((3,3))
print(matrix_one)

Soma (a + c):  [ 5  6  7  8  9 10]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
# Operações

np.sum(a)
np.prod(a)
np.mean(a)
np.std(a) #desvio padrao
np.max(a)
np.argmax(a)
np.min(a)


In [24]:
# Comparação

print("Comparação: ", a> 2)
print("Filtro: ", a[a > 3])
print("AND Lógico: ", (a> 1) & (a <4))

Comparação:  [False False  True  True  True  True]
Filtro:  [4 5 6]
AND Lógico:  [False  True  True False False False]


# Exercícios com NumPy - Operações Simples com Vetores e Matrizes

## Exercício 1: Cálculo de Média Ponderada

Você é professor de uma disciplina e precisa calcular a nota final dos alunos usando um sistema de pesos diferentes para cada avaliação.

Dados:
- Notas de um aluno: `[7.5, 8.0, 6.5, 9.0]` (quatro avaliações)
- Pesos respectivos: `[0.2, 0.3, 0.2, 0.3]`

**Sua tarefa:**
1. Crie dois arrays NumPy com os dados fornecidos
2. Calcule a média ponderada usando operações vetorizadas
3. Arredonde o resultado para 1 casa decimal
4. Exiba o resultado final

**Dica:**  
Lembre-se que média ponderada = Σ(nota × peso) / Σ(pesos)

In [27]:
notas = np.array([7.5, 8.0, 6.5, 9.0])
pesos = np.array([0.2, 0.3, 0.2, 0.3])

soma = (notas*pesos)
print("Media ponderada: ", np.sum(soma)/np.sum(pesos))

Media ponderada:  7.9


## Exercício 2: Conversão de Temperaturas

Você está trabalhando com dados meteorológicos e precisa converter uma série de temperaturas de Celsius para Fahrenheit.

Dados:
- Temperaturas em Celsius: `[0, 10, 20, 30, 40]`

**Sua tarefa:**
1. Crie um array NumPy com as temperaturas em Celsius
2. Aplique a fórmula de conversão:  
   `Fahrenheit = (Celsius × 9/5) + 32`
3. Crie um novo array com as temperaturas convertidas
4. Exiba ambos os arrays (Celsius e Fahrenheit) para comparação

**Dica:**  
NumPy permite aplicar operações matemáticas a arrays inteiros sem necessidade de loops.

In [30]:
celsius = np.array([0, 10, 20, 30, 40])

fah = np.array((celsius*9/5) + 32)

print("Celsius: ", celsius)
print("Fahrenheit: ", fah)


Celsius:  [ 0 10 20 30 40]
Fahrenheit:  [ 32.  50.  68.  86. 104.]


# Exercício 3: Sistema de Pontuação de Atividades Físicas

Você está desenvolvendo um sistema de acompanhamento de atividades físicas que registra:
- Quantidade de minutos de exercício por dia
- Pontos conquistados (cada minuto = 1 ponto)
- Bônus diário (5 pontos para dias com >30 minutos)

Dados da última semana:

Segunda: 25 min
Terça: 40 min
Quarta: 30 min
Quinta: 55 min
Sexta: 20 min
Sábado: 60 min
Domingo: 45 min

1. Crie uma matriz NumPy 7x3 (dias × dados) contendo:
   - Coluna 1: minutos de exercício
   - Coluna 2: pontos base (1 por minuto)
   - Coluna 3: bônus (5 pontos se minutos >30)

2. Calcule:
   - Total de minutos na semana
   - Total de pontos (base + bônus)
   - Dia com maior atividade física

In [37]:
diasDados = np.ones((7,3))

pontos = np.array([25,40,30,55,20,60,45])
bonus = np.where(pontos > 30, diasDados())
print(diasDados)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
